baseurl = "https://angelroddy.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "Angel Rodriguez"
theme = "hugo-theme-dream"

copyright = "Angel Rodriguez"

# googleAnalytics = ""

disqusShortname = "disqus_0pOA5fAtDy"

# enableRobotsTXT = true

[params]
  author = "Angel"
  motto = "Front-End Web Developer"
  description = "A place to blog"
  avatar = "https://res.cloudinary.com/angelrodriguez/image/upload/v1541444428/Screen_Shot_2018-11-05_at_1.56.56_PM.png"
  
  email = "angelr1076@gmail.com"
  github = "www.github.com/angelr1076/"
  linkedin = "www.linkedin.com/in/angelrodriguezlead/"
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2018
  aboutHeader = "About Me"

  paginate = 4

  favicon = "https://res.cloudinary.com/angelrodriguez/image/upload/c_scale,h_20,w_20/v1528903608/4.ico"
